#:schema node_modules/wrangler/config-schema.json
name = "todos"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "todo-list"
database_id = "499988fd-d370-4671-9cd9-da5a69402f9e"
