import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Todo App',
	description: 'Generated by create next app',
};

const navigation = [
	{ name: 'Home', href: '/' },
	{ name: 'Todos', href: '/todos' },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header>
					<nav>
						{navigation.map((item) => (
							<Link key={item.name} href={item.href}>
								{item.name}
							</Link>
						))}
					</nav>
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
