import Link from 'next/link';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ReactQueryProvider from '@/app/context/react-query';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Todo App',
	description: 'Generated by create next app',
};

const navigation = [
	{ name: 'Home', href: '/' },
	{ name: 'Todos', href: '/todos' },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReactQueryProvider>
			<html lang="en">
				<body className={inter.className}>
					<header className="flex p-4">
						<nav className="flex flex-row gap-2 underline">
							{navigation.map((item) => (
								<Link key={item.name} href={item.href}>
									{item.name}
								</Link>
							))}
						</nav>
					</header>
					<main className="flex flex-col gap-2 p-4">{children}</main>
				</body>
			</html>
		</ReactQueryProvider>
	);
}
