import Link from 'next/link';
import { Viewport } from 'next';
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import Auth from '@/components/auth';
import ReactQueryProvider from '@/app/context/react-query';
import DarkMode from '@/components/dark-mode';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Todo App',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const theme = cookieStore.get('theme');
	const darkMode = theme?.value === 'dark';

	return (
		<ClerkProvider>
			<ReactQueryProvider>
				<html lang="en" className={darkMode ? 'dark' : ''}>
					<body className={inter.className}>
						<header className="flex flex-row items-center  px-4 py-2">
							<div className="flex flex-row gap-2 ml-auto">
								<DarkMode mode={darkMode} />
								<Auth />
							</div>
						</header>
						<main className="flex flex-col gap-2 p-4">
							{children}
						</main>
					</body>
				</html>
			</ReactQueryProvider>
		</ClerkProvider>
	);
}
